### ISSUE TITLE
showid: 间隔样式实现重构

### ISSUE THREAD

**Issue by CKylinMC** [CKylinMC/UserJS#29]
```css
#bilibiliShowInfos {
  display: inline-flex;
  column-gap: 16px;
}
```
https://greasyfork.org/zh-CN/scripts/398655/discussions/99054#comment-231782
